### PR TITLE
fix compatibility with modern numpy

### PR DESCRIPTION
**Pull request by Migelo**
Using pmesh with number newer that circa `1.21` results in an error when trying to assign edges as
```python
self.edges = numpy.asarray(edges)
```
This pull request fixes this by replacing the line above with
```python
self.edges = [numpy.asarray(g) for g in edges]
```
It also modernizes the repo by adding `pyproject.toml` file. 

I will create this as a draft, so that the original author @adematti signs off on this.

### CODE REVIEW

**Comment by Migelo** [comment]
I just tested it with `python3.10` and it works :)

**Comment by Migelo** [comment]
It seems that https://github.com/rainwoodman/pmesh/pull/47 fixes the main issue this PR is solving.

**Comment by Migelo** [comment]
Hey @adematti, would you be ok if I open this pull request?

**Comment by adematti** [comment]
of course, no prob! the pyproject.toml makes sure numpy and cython get installed before setup.py is run

**Comment by adematti** [comment]
I think @rainwoodman needs to solve the conflict (`self.edges = [numpy.asarray(g) for g in edges]` seems to me a slightly better solution than casting to object type)

**Comment by rainwoodman** [comment]
Done!

**Comment by adematti** [comment]
Thanks! :)

**Pull request merged**
