### PR TITLE
assert on size needs to be collective in unravel

### PR DESCRIPTION
**Pull request by nickhand**
apologies for the newline fixes....only change is:

assert self.pm.comm.allreduce(len(flatiter)) == self.csize

on line 330

### CODE REVIEW

**Comment by nickhand** [comment]
does this look okay to you, @rainwoodman ?

**Comment by rainwoodman** [comment]
Yes this looks good. The travis error is unrelated.

**Comment by nickhand** [comment]
do you want to hold off on putting out a new version until Travis errors are cleaned up?

**Comment by rainwoodman** [comment]
Yes. I am doing that. The travis light will be green after abopt is pushed. I think we shall move the abopt interface to somewhere else to avoid this dependency.

**Comment by nickhand** [comment]
Great, we'll be able to merge in my latest nbodykit ``docs`` branch then with the ArrayMesh object added then.

**Comment by rainwoodman** [comment]
Travis is green  -- I'll tag a release.

**Pull request merged**
