### PR TITLE
Balance the load among different ranks

### PR DESCRIPTION
**Pull request by rainwoodman**
Add two functions in domain.py. load() will calculate the load of each domain, and loadbalance() will assign domains to ranks so that every rank has comparable loads.
The assignment result is recorded in the array DomainAssign, which will be used in the function decompose().
Each rank will have several domains (primary regions).

### CODE REVIEW

**Comment by rainwoodman** [comment]
@biweidai Could you do some additional testing to see if my commits mess it all up?

**Comment by biweidai** [comment]
I did not find any bugs in the code. I have run several simple tests (including the degenerate case), and I will test it in my PP short range force code.

**Comment by nickhand** [comment]
Shall I try this out on SurveyDataPairCount to see if bccp/nbodykit#364 is fixed?

**Comment by rainwoodman** [comment]
yes. but you probably still need to create an over decomposition grid in
nbodykit to trigger this?

On Sep 20, 2017 5:29 PM, "Nick Hand" <notifications@github.com> wrote:

Shall I try this out on SurveyDataPairCount to see if bccp/nbodykit#364
<https://github.com/bccp/nbodykit/issues/364> is fixed?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/rainwoodman/pmesh/pull/26#issuecomment-331017492>, or mute
the thread

**Pull request merged**
